-- create the items table
CREATE TABLE items(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label text NOT NULL,
    built_at int REFERENCES items ON UPDATE CASCADE,
    icon_url text,
    default_colour char(6) DEFAULT upper(substr(md5(random()::text), 0, 7))
);

-- create the dependencies table
CREATE TABLE dependencies(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id int NOT NULL REFERENCES items ON DELETE CASCADE ON UPDATE CASCADE,
    target_id int NOT NULL REFERENCES items ON DELETE CASCADE ON UPDATE CASCADE,
    amount int DEFAULT 0
);

-- create the tags table
CREATE TABLE tags(
    name text PRIMARY KEY,
    description text
);

-- create the item / tag relationship table
CREATE TABLE item_tags(
    item_id int NOT NULL REFERENCES items ON DELETE CASCADE ON UPDATE CASCADE,
    tag_name text NOT NULL REFERENCES tags ON DELETE CASCADE ON UPDATE CASCADE,
    PRIMARY KEY(item_id, tag_name)
);